### ISSUE TITLE
Is it a Indian/Global or Chinese version?

### ISSUE THREAD

**Issue by seekerzz** [mauronofrio/android_device_realme_RMX1901#1]
Hello, I'm a RealmeX user in China, today we may have our bootloader unlocked, so we are going to try TWRP. However, no official download is provided. I searched it and saw your work, is it a Indian/Global or Chinese version? (Or it doesn't matter which version the phone is?) Thank you so much!

**Comment by mauronofrio** [comment]
No matter which version you are using

**Comment by mauronofrio** [comment]
Look that touchscreen is not working

**Comment by seekerzz** [comment]
Thanks for your quick reply! We got official ROM and BL unlock(maybe) today, so we are excited to see your great work.I also saw you on Chinese Realme bbs, people are looking forward to your further development👍

**Comment by mauronofrio** [comment]
Oh thanks, but I'm not on Chinese Realme bbs, can you link me it?

**Comment by seekerzz** [comment]
Official ozip:
https://www.realme.com/support/software-update

BL unlock(just a few minutes ago)
https://www.realmebbs.com/post-details/1163703236419399680

People who saw your work:
https://www.realmebbs.com/post-details/1163724162963877888

**Comment by mauronofrio** [comment]
Thanks, as i already said, my twrp has a touchscreen problem so for now i have not pubblished the twrp.but only the source on github. I think that all others things are working good.

**Comment by JoshDaone** [comment]
Thanks bro, appreciate it

**Comment by mauronofrio** [comment]
TWRP is released, enjoy:

https://forum.xda-developers.com/realme-x/development/recovery-unofficial-twrp-realme-x-stable-t3959556
https://github.com/mauronofrio/android_device_realme_RMX1901/releases/tag/9
